#!/bin/sh

# Log the current operation
echo "Elevating configuration files in $SYNOPKG_CONF..."
echo "Currently running as user: $(whoami)"

# Test is running as root
if [ "$(id -u)" -ne 0 ]; then

    echo "This script must be run as root to elevate configuration files."

    if [ -n "$SYNOPKG_PKG_STATUS" ] && [ "$SYNOPKG_PKG_STATUS" = "INSTALL" ]; then
        echo "Package will now show in Error in Package Center, and will be functional when elevated."
        echo "See https://synopkghub.perspikapps.eu/elevate for more information."
    fi >${SYNOPKG_TEMP_LOGFILE:-/dev/stderr}

    exit 150
fi

# merge $CONF_DIR/%.elevated files into $CONF_DIR/% (all content is json)
ls -1 $SYNOPKG_CONF/*.elevated 2>/dev/null | while read -r file; do
    base=$SYNOPKG_CONF/$(basename "$file" .elevated)

    if [ -f "$base" ]; then
        echo "Merging $file into $base"
        jq -s '.[0] * .[1]' "$base" "$file" >/tmp/$$.elevated && mv "/tmp/$$.elevated" "$base"
    else
        echo "No base file for $file, creating new one"
        cp "$file" "$base"
    fi
done
