#!/bin/sh

# This script runs the preset scripts in the current directory for a given script context.
export SUBST_INPUT_FILE=$1
export SUBST_OUTPUT_FILE=$2
export SUBST_KEY=$3
export SUBST_KEY_FILE="$SYNOPKG_PKGCONF/subst.$SUBST_KEY.env"

# Check if the context is provided
if [ -z "$SUBST_INPUT_FILE" ] || [ -z "$SUBST_OUTPUT_FILE" ]; then
    echo "Usage: $0 <input> <output>"
    exit 1
fi

# Source previously set variables from the wizard file
if [ -f "$SUBST_KEY_FILE" ]; then
    . $SUBST_KEY_FILE
fi

# Prepare the output directory
mkdir -p $(dirname "$SUBST_OUTPUT_FILE")
cp "$SUBST_INPUT_FILE" "$SUBST_OUTPUT_FILE"

# Extract variables from the output file
vars=$(grep -oP "{{\s*$SUBST_KEY.\w+\s*}}" "$SUBST_OUTPUT_FILE" | sed 's/{{\s*//; s/\s*}}//')

# Loop through each variable found in the output file
for var in $vars; do
    echo "Substituting variable: $var"

    value=$(eval echo "\$${var#wizard.}")

    if [ -z "$value" ]; then
        echo "Warning: Variable ${var#wizard.} is not set or empty."
        continue
    fi

    if [ "$value" = "null" ]; then
        $value=""
    fi

    # Udpate the output file with the variable value
    sed -i "s|{{\s*$var\s*}}|$value|g" "$SUBST_OUTPUT_FILE"

    # if variable is not found in wizard file, add it to the wizard file
    grep -q "^$var=" "$SUBST_KEY_FILE" || echo "$var=$value" >>"$SUBST_KEY_FILE"

done
