#!/bin/sh

# This script runs the preset scripts in the current directory for a given script context.
export SUBST_INPUT_FILE=$1
export SUBST_OUTPUT_FILE=$2
export SUBST_KEY=$3


# Check if the context is provided
if [ -z "$SUBST_INPUT_FILE" ] || [ -z "$SUBST_OUTPUT_FILE" ]; then
    echo "Usage: $0 <input> <output>"
    exit 1
fi

# Source previously set variables from the wizard file
export SUBST_KEY_FILE="$SYNOPKG_PKGHOME/$SUBST_KEY.subst.env"
if [ -f "$SUBST_KEY_FILE" ]; then
    . $SUBST_KEY_FILE
fi

# Prepare the output directory
if [ $(readlink -f "$SUBST_INPUT_FILE") != $(readlink -f "$SUBST_OUTPUT_FILE") ]; then
    mkdir -p $(dirname "$SUBST_OUTPUT_FILE")
    cp -f "$SUBST_INPUT_FILE" "$SUBST_OUTPUT_FILE"
else
    echo "In-place substitution detected"
fi

# Extract variables with the specified key from the input file
vars=$(grep -oP "{{\s*\w+\s*}}" "$SUBST_INPUT_FILE" | sed 's/{{\s*//; s/\s*}}//')

# Loop through each variable found in the output file
for var in $vars; do

    echo "Substituting variable: $var"

    # Check if the variable without the key is set in the environment
    value=$(eval echo "\$${var}")

    if [ -z "$value" ]; then
        echo "Warning: Variable ${var} is not set or empty."
        continue
    fi

    if [ "$value" = "null" ]; then
        $value=""
    fi

    # Udpate the output file with the variable value
    sed -i "s|{{\s*$var\s*}}|$value|g" "$SUBST_OUTPUT_FILE"

    # if variable is not found in wizard file, add it to the wizard file
    if [ -f "$SUBST_KEY_FILE" ]; then
        grep -q "^export ${var}=" "$SUBST_KEY_FILE" || echo "export ${var}=$value" >>"$SUBST_KEY_FILE"
    else 
        echo "Substitution env file not found"
    fi

done
