name: Synology Package Builder Github Action
author: tomgrv
description: Build Synology packages
branding:
  icon: 'package'
  color: 'blue'
inputs:
  dsm:
    description: 'Version of DSM to build for'
    required: true
    default: '7.0'
  arch:
    description: 'Architecture to build for'
    required: true
    default: 'noarch'
  projects:
    description: 'List of project to build'
    required: true
    default: 'package:./src'
  output:
    description: 'Packages folder'
    required: false
    default: 'bin'
runs:
  using: "composite"
  steps:
    - id: hash
      run: |
        echo "docker=$(sha256sum ${{ github.action_path }}/dockerfile | cut -c 1-7)" >> $GITHUB_OUTPUT
        echo "build=$(sha256sum ${{ github.action_path }}/build | cut -c 1-7)" >> $GITHUB_OUTPUT
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: ${{ github.action_path }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: build:${{ steps.hash.outputs.docker }}${{ steps.hash.outputs.build }}
        load: true
        file: ${{ github.action_path }}/dockerfile
    - uses: actions/cache@v2
      with:
        path: |
          /toolkit/toolkit_tarballs
          /toolkit/pkgscripts-ng
        key: toolkit-${{ inputs.dsm }}-${{ inputs.arch }}
    - run: /usr/bin/docker run --quiet 
             --workdir /workspace --rm --privileged
             --entrypoint "/build"
             $((test -n "${{ github.env }}" && cat ${{ github.env }} || echo "") | sed 's/^\([A-Za-z_][A-Za-z0-9_]*\)=\(.*\)/--e \1=\2/g' )
             -v /var/run/docker.sock:/var/run/docker.sock
             -v /toolkit:/toolkit
             -v "${{ github.workspace }}":"/workspace" 
             build:${{ steps.hash.outputs.docker }}${{ steps.hash.outputs.build }} -v ${{ inputs.dsm }} -p ${{ inputs.arch }} ${{ inputs.projects }}
      shell: bash
    - id: artifacts
      run: |
        find /toolkit/result_spk/ ! -type d -name "*.spk"  ! -path "*.bad.*" -exec cp {} ${{ github.workspace }}/.spk \;
        echo "packages=${{ github.workspace }}/.spk" >> $GITHUB_OUTPUT
      