#!/bin/sh

# Default DSM version and arch
#  ↓
export DSM=7.0
export ARCH=avoton
export WORKSPACE=$(test -d /workspace && echo "/workspace" || readlink -f $(dirname $0))
export TOOLKIT=/toolkit
export CONFIG=$WORKSPACE/package.json
export OUTPUT=$WORKSPACE/bin
export STUBS=$WORKSPACE/stubs

# Parse script arguments for dsm version and arch
#  ↓
while getopts ":v:p:o:c:s:" opt; do
    case $opt in
    v)
        export DSM="$OPTARG"
        shift 2
        ;;
    p)
        export ARCH="$OPTARG"
        shift 2
        ;;
    o)
        export OUTPUT=$(readlink -f $OPTARG)
        shift 2
        ;;
    c)
        export CONFIG=$(readlink -f $OPTARG)
        shift 2
        ;;
    s)
        export STUBS=$(readlink -f $OPTARG)
        shift 2
        ;;
    \?)
        echo "Invalid option -$OPTARG" >&2
        exit 1
        ;;
    esac
done

echo "::group::Building packages for DSM$DSM on $ARCH"

echo "Workspace: $WORKSPACE"
echo "DSM version: $DSM"
echo "Architecture: $ARCH"
echo "Config: $CONFIG"
echo "Output folder: $OUTPUT"
echo "Stubs folder: $STUBS"

# Prepare build environment
# https://help.synology.com/developer-guide/getting_started/prepare_environment.html
#  ↓
if [ ! -d "$TOOLKIT/pkgscripts-ng" ]; then
    git clone https://github.com/SynologyOpenSource/pkgscripts-ng $TOOLKIT/pkgscripts-ng
fi

# Make sure the OUTPUT folder exists
#  ↓
mkdir -p $OUTPUT

# Set safe directory
#  ↓
git config --global --add safe.directory $TOOLKIT/pkgscripts-ng

# Check if the Arch is supported
#  ↓
if [ "$ARCH" != "noarch" ]; then

    echo "::group::Deploy Chroot Environment For $ARCH NAS Target"

    # Deploy Chroot Environment For Different NAS Target
    # https://help.synology.com/developer-guide/getting_started/prepare_environment.html
    #  ↓
    if [ ! -d "$TOOLKIT/build_env/ds.$ARCH-$DSM" ] || [ ! -f "$TOOLKIT/build_env/ds.$ARCH-$DSM/PkgVersion" ]; then
        mkdir -p $TOOLKIT/build_env
        cd $TOOLKIT/pkgscripts-ng/
        git checkout DSM$DSM || exit 1
        ./EnvDeploy --version $DSM -p $ARCH || exit 1
        cd -
    fi

    echo "::endgroup::"
fi

# Reset source folder link
#  ↓
echo "::group::Reset source folder"
rm -rf $TOOLKIT/source
mkdir -p $TOOLKIT/source
echo "::endgroup::"

# For each project in subsequent arguments in the form of name:folder, create a symlink to the folder and build
# https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#workdir
#  ↓
while [ $# -gt 0 ]; do

   

    case "$1" in
    *:*)
        SOURCE=${1#*:}
        PACKAGE=${1%:*}
        ;;
    .*)
        SOURCE=$1
        PACKAGE=$(basename $1)
        ;;
    esac


    # Check source folder
    if [ ! -d "$WORKSPACE/$SOURCE" ]; then
        echo "Source folder $WORKSPACE/$SOURCE does not exist"
        exit 1
    fi

    # Prepare with stubs files
    echo "Copy /stubs -> $TOOLKIT/source/$PACKAGE"
    cp -rfp $STUBS $TOOLKIT/source/$PACKAGE || exit 1

    # Copy package source
    echo "Copy $WORKSPACE/$SOURCE -> $TOOLKIT/source/$PACKAGE"
    cp -rfp "$WORKSPACE/$SOURCE/"* "$TOOLKIT/source/$PACKAGE/" || exit 1

    # Copy config file
    echo "Copy $CONFIG -> $TOOLKIT/source/$PACKAGE/config.json"
    cp -f "$CONFIG" "$TOOLKIT/source/$PACKAGE/config.json" || exit 1

    # Build
    cd $TOOLKIT
    echo "::group::Build $PACKAGE for DSM$DSM on $ARCH"
    pkgscripts-ng/PkgCreate.py --print-log  -c -p $ARCH -v $DSM $PACKAGE || exit 1
    echo "::endgroup::" 

    # Push to output folder
    echo "::group::Collect $PACKAGE for DSM$DSM on $ARCH"
    find $TOOLKIT/result_spk/ ! -type d -name "*.spk" ! -path "*.bad.*" -exec cp {} $OUTPUT/ \;
    echo "::endgroup::"

    # Next package
    shift
done

echo "::endgroup::"
