#!/bin/sh

# Define build script
#  ↓
BUILD=./build

# If docker requested, build docker image and override build script
#  ↓
if [ "$1" = "--with-docker" ]; then
    echo "Building image..."
    docker build -t build:latest -f "./dockerfile" "."
    echo "Done."
    BUILD="docker run --privileged --rm \
                    --workdir /github/workspace \
                    -v "/var/run/docker.sock":"/var/run/docker.sock" \
                    -v $PWD:/github/workspace build:latest"
fi

# Prepare test environment
# https://help.synology.com/developer-guide/getting_started/first_package.html
#  ↓
rm -rf src
git clone https://github.com/SynologyOpenSource/ExamplePackages src

# Build Packages
# https://help.synology.com/developer-guide/getting_started/first_package.html
#  ↓
find ./src -maxdepth 1 -type d ! -name ".*" ! -name "src" -exec echo {} \; | while read -r project; do
    echo "Building $project"
    $BUILD -v 7.0 -p avoton $project || exit 1
done
