#!/bin/bash

# 심볼릭 링크 생성 (DSM 웹 인터페이스용)
ln -sf /var/packages/ChangePanelSize/target/app /usr/syno/synoman/webman/3rdparty/ChangePanelSize

# 권한 설정
chmod +x /var/packages/ChangePanelSize/target/bin/change_panel_size.py

exit 0

