## spk/ChangePanelSize/Makefile

## 패키지 메타정보
SPK_NAME           = ChangePanelSize
SERVICE_USER       = sc-Changepanelsize

## 서비스 포트 정의 (기본 TCP 프로토콜, 예: 8089번 포트)
SERVICE_PORT       = 8089

## TCP·UDP를 모두 허용하려면
# SERVICE_PORT     = tcp/8089,udp/8089

## HTTPS 포트만 정의하려면 (‘https’로 구분)
# SERVICE_PORT_HTTPS = 443

include ../../mk/spksrc.spk.mk
