#!/bin/sh

for i in $TARGET_PATH/config/*; do
    if [ -f "$i" ]; then
        
        echo "Processing $i"

        IMAGE_NAME=$(jq -r '.image' $i)
        IMAGE_TAG=$(echo $IMAGE_NAME | cut -d':' -f2)
        IMAGE_REPO=$(echo $IMAGE_NAME | cut -d':' -f1)
        IMAGE_FILE=$IMAGE_NAME.tar.xz

        $DOCKER_BIN rmi "$IMAGE_FULL_DOCKER_LATEST"
        $DOCKER_BIN tag "$IMAGE_FULL_DOCKER" "$IMAGE_FULL_DOCKER_LATEST" || exit 1

        $CONTAINERMANAGER_TARGET_PATH/tool/helper "$IMAGE_NAME" "$IMAGE_TAG" "$TARGET_PATH/docker/$IMAGE_FILE" $SIZE_UNOCONV

        $WEBAPI_BIN --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false profile="$(cat "$TARGET_PATH/conf/$i")" || exit 1

        rm -f "$TARGET_PATH/docker/$IMAGE_FILE"
    fi
done
