#!/bin/sh

### Init port file
PORT_CONFIG_FILE="/var/packages/$SYNOPKG_PKGNAME/etc/port_config"

### Remove the port file
if [ "$SYNOPKG_PKG_STATUS" = "UNINSTALL" ]; then
    rm -f "$PORT_CONFIG_FILE"
fi

exit 0
