#!/bin/sh

case "$1" in
  start)
    nohup /var/packages/Changepanelsize/target/bin/change_panel_size.py >> /var/log/Changepanelsize/python.log 2>&1 &
    ;;
  stop)
    pkill -f change_panel_size.py
    ;;
  status)
    pgrep -f change_panel_size.py >/dev/null
    ;;
esac
exit 0
